config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/shop', to: 'shop#index'
  resources :supports
  get 'users/index'
  get 'users/show'
  get '/support' ,to: 'support#index'
  get '/resource',to: 'resource#index'

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'

  resources :succours
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/support.rb
class Support < ApplicationRecord
  extend FriendlyId
  friendly_id :subject, use: :slugged
  belongs_to :user
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  before_action :set_support, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user_for_support, only: [:edit, :update, :destroy]
  before_action :current_user_support, only:[:show]
  # GET /supports
  # GET /supports.json
  def index
    @supports = Support.paginate(:page => params[:page], :per_page => 3).order("created_at DESC")
  end

  # GET /supports/1
  # GET /supports/1.json
  def show
  end

  # GET /supports/new
  def new
    @support = current_user.supports.build
  end

  # GET /supports/1/edit
  def edit
  end

  # POST /supports
  # POST /supports.json
  def create
    @support = current_user.supports.build(support_params)

    respond_to do |format|
      if @support.save
        format.html { redirect_to @support, notice: 'Support was successfully created.' }
        format.json { render :show, status: :created, location: @support }
      else
        format.html { render :new }
        format.json { render json: @support.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supports/1
  # PATCH/PUT /supports/1.json
  def update
    respond_to do |format|
      if @support.update(support_params)
        format.html { redirect_to @support, notice: 'Support was successfully updated.' }
        format.json { render :show, status: :ok, location: @support }
      else
        format.html { render :edit }
        format.json { render json: @support.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supports/1
  # DELETE /supports/1.json
  def destroy
    @support.destroy
    respond_to do |format|
      format.html { redirect_to supports_url, notice: 'Support was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_support
      @support = Support.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def support_params
      params.require(:support).permit(:subject, :message, :user_id, :slug)
    end

    # check if the user is authorised to edit,update or destroy the cv
    def correct_user_for_support
      @support = current_user.supports.find_by(params[:friendly])
          redirect_to supports_path, notice: "Not authorised to edit this support" if @support.nil?
    end
    # check if  cv belongs to the correct user - current user
      def current_user_support
        if user_signed_in?
         @supports = current_user.supports.order("created_at DESC")
       end
     end
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/supports/_contact_details.html.erb
<ul class="list-unstyled mb-3">
  <li class="mb-1"><i class="fas fa-envelope-square"></i> Felender7@gmail.com</li>
  <li class="mb-1"><i class="fab fa-discord"></i> Discord:Felender#3712 </li>
  <li class="mb-1"><a href="#"><i class="fab fa-whatsapp-square"></i> WhatsApp Group</a></li>
  <li class="mb-1"><i class="fas fa-phone-square-alt"></i> 081 407 5744</li>
</ul>

app/views/supports/_form.html.erb
<div class="container-fluid mt-3">
<%= form_with(model: support, local: true, class:"was-validated") do |form| %>
<div class="row">
  <div class="col-lg-8">
   <div class="shadow-sm p-3 mb-5 bg-light">
  <% if support.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(support.errors.count, "error") %> prohibited this support from being saved:</h2>

      <ul>
      <% support.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :subject, class: 'form-control', placeholder:"Subject" , required: :required %>
  </div>

  <div class="form-group">
    <%= form.text_area :message, class: 'form-control', placeholder:"Start typing...", required: :required %>
  </div>

  <div class="form-group">
    <% if support.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', support, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.button(type: "submit", class: "btn btn-primary" , data: {disable_with:"<i class='fa fa-spinner fa-spin'></i> Saving..." .html_safe }) do %>
       <i class="far fa-paper-plane"></i> SEND
    <% end %>

    <% if support.persisted? %>
      <%= link_to "Cancel", support, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", supports_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>
</div>
</div>
<div class="col-lg-4">
  <%=render'shared/donate'%>
</div>
</div>
</div>

app/views/supports/_table_content.html.erb
<%if current_user.supports.exists?%>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <tbody>
      <% @supports.each do |support| %>
        <%= content_tag :tr, id: dom_id(support), class: dom_class(support) do %>
        <% if current_user && support.user == current_user %>
                      <td><%= support.subject %><br>
                       <small><span class="text-success"><%=time_ago_in_words(support.created_at) +" ago" %></span></small>
                      </td>
                      <td>
                        <%=truncate(support.message.html_safe, length: 30) %>
                      </td>
            <td><%= link_to support do %>
              <i class="far fa-list-alt"></i>
               <%end%>
            </td>
          <%end%>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @supports, list_classes: %w(pagination justify-content-end),renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
<%else%>

<div class="bg-light text-primary text-center p-3">
  <i class="far fa-folder-open fa-2x"></i> <br>
<p>Nothing yet!</p>
</div>

<%end%>

app/views/supports/edit.html.erb
<div class="container-fluid mt-5">
  <div class="shadow-sm p-3  bg-dark text-light border-top-reviews  ">
     <h4><i class="fas fa-info-circle"></i> Edit Message</h4>
   </div>
</div>

<%= render 'form', support: @support %>

app/views/supports/index.html.erb
<div class="container-fluid mt-5 ">
  <div class="shadow-sm p-3 bg-dark text-light border-top-reviews">
    <div class="row">
      <div class="col-md-8 col">
        <h4><i class="far fa-list-alt"></i> How can we help?</h4>
      </div>
      <div class="col">
        <%= link_to new_support_path, class: 'btn btn-primary btn-sm float-right' do %>
        <i class="fas fa-plus-square"></i> Compose
        <% end %>
      </div>
    </div>
  </div>


  <div class="shadow-sm p-3 mb-5 bg-white">
  <div class="row">
    <div class="col-lg-12">
      <div class="row">
        <div class="col-lg-6">
          <h5><i class="fas fa-id-card-alt"></i> Contacts</h5>
          <hr>
            <%=render'supports/contact_details'%>
          </div>

          <div class="col-lg-6">
            <p>Sent <span class="badge bg-danger text-light"><%=@support_count%> </span></p>
               <%=render'supports/table_content'%>
          </div>
      </div>
      </div>
      </div>
  </div>
</div>

app/views/supports/new.html.erb
<div class="container-fluid mt-5">
  <div class="shadow-sm p-3  bg-dark text-light border-top-reviews  ">
     <h4><i class="fas fa-info-circle"></i> Compose Message</h4>
   </div>
</div>

<%= render 'form', support: @support %>

app/views/supports/show.html.erb
<div class="container-fluid mt-5">

<div class="shadow-sm p-3 text-light bg-dark border-top-reviews">
    <div class="row">
      <div class="col-md-8">
        <h4><i class="far fa-list-alt"></i> <%=@support.subject%></h4>
      </div>
      <div class="col-md-4">
        <a href="/supports" class="float-right text-danger"> <i class="fa fa-window-close" data-toggle="tooltip" title="Close"> </i></a>
      </div>
    </div>
</div>

<div class="shadow-sm p-3 mb-5 bg-white">
<div class="row">
  <div class="col-lg-8">
<div class="p-3 bg-light">
<p><strong>To:</strong>admin@octal.co.za </p>
<p><%= @support.message %></p>
</div>
<hr>
   <%= link_to edit_support_path(@support), class: 'btn btn-warning btn-sm' do %>
     Edit
   <% end %>
</div>
<div class="col-lg-4">
  <%=render'shared/donate'%>
</div>
</div>
</div>
</div>
<br><br><br>